spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spatial-sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL5SpatialDialect
        show_sql: true  # Debug sql statement

server:
  port: 8080

logging.level.org.hibernate.type: trace # Debug spatial type working or not